### PR TITLE
Create archiver.py

### PR DESCRIPTION
**Pull request by pandaxtc**

### CODE REVIEW

**Comment by Avuxo** [comment]
Crashes when using large files. Do not load all files into memory at once, instead create a file stream.

Reproduce:
`$ mkdir archive && cd archive && fallocate -l 1G 01 && fallocate -l 1G 02 && cd .. && ./archive.py archive -o 01`

**Comment by pandaxtc** [comment]
> Crashes when using large files. Do not load all files into memory at once, instead create a file stream.
> 
> Reproduce:
> `$ mkdir archive && cd archive && fallocate -l 1G 01 && fallocate -l 1G 02 && cd .. && ./archive.py archive -o 01`

Fixed.

**Comment by Avuxo** [comment]
One additional feature request before I give this the thumbs up: Could you make the first section of the header before listing file locations the number of files so that a header structure can be allocated in the engine more easily?

Edit: this is already done.

**Comment by pandaxtc** [comment]
It should already contain that information at exactly that spot

**Review by Avuxo — APPROVED** [review]
lgtm, go ahead and merge it
Once you've done that, please give a header and file contents description in the wiki so that I can parse this guy.

**Pull request merged**
